import { Wine } from '@/types/wine';

export const mockWines: Wine[] = [
  // Red Wines
  {
    id: '1',
    slug: 'chateau-margaux-2015',
    name: 'Château Margaux',
    vintage: 2015,
    category: 'red',
    price: 89.95,
    image: 'https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?w=800&q=80',
    images: [
      'https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?w=800&q=80',
      'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80'
    ],
    description: 'Een prestigieuze Bordeaux wijn van een van de meest gerenommeerde châteaux in de Margaux appellation. Dit vintage toont elegante tannines en complexe fruitsmaken.',
    tastingNotes: 'Tonen van zwarte bessen, ceder en subtiele tabak. Zijdeachtige tannines met een lange, verfijnde afdronk.',
    foodPairing: 'Perfect bij gegrild lamsvlees, gerijpte kazen of ossenhaas.',
    region: 'Bordeaux, Frankrijk',
    grapeVariety: ['Cabernet Sauvignon', 'Merlot', 'Cabernet Franc'],
    alcoholPercentage: 13.5,
    volume: 750,
    servingTemperature: '16-18°C',
    inStock: true,
    featured: true,
  },
  {
    id: '2',
    slug: 'barolo-riserva-2016',
    name: 'Barolo Riserva',
    vintage: 2016,
    category: 'red',
    price: 64.50,
    image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80'],
    description: 'De "Koning van Wijnen" uit Piemonte, Italië. Deze Barolo Riserva biedt krachtige structuur en verouderingspotentieel.',
    tastingNotes: 'Kers, rozenblaadjes, teer en truffel. Stevige tannines met uitstekende diepte.',
    foodPairing: 'Ideaal bij gestoofde vlees, risotto met truffels of gerijpte harde kazen.',
    region: 'Piemonte, Italië',
    grapeVariety: ['Nebbiolo'],
    alcoholPercentage: 14.0,
    volume: 750,
    servingTemperature: '18-20°C',
    inStock: true,
    featured: false,
  },
  {
    id: '3',
    slug: 'rioja-gran-reserva-2014',
    name: 'Rioja Gran Reserva',
    vintage: 2014,
    category: 'red',
    price: 42.95,
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80'],
    description: 'Een klassieke Spaanse rode wijn met uitgebreide rijping in eiken vaten, die soepele complexiteit biedt.',
    tastingNotes: 'Rode vruchten, vanille, leer en kruiden. Goed geïntegreerde eik met fluwelen textuur.',
    foodPairing: 'Prachtig bij geroosterd lamsvlees, chorizo of manchego kaas.',
    region: 'Rioja, Spanje',
    grapeVariety: ['Tempranillo', 'Garnacha'],
    alcoholPercentage: 13.5,
    volume: 750,
    servingTemperature: '16-18°C',
    inStock: true,
    featured: true,
  },
  {
    id: '4',
    slug: 'cotes-du-rhone-villages-2020',
    name: 'Côtes du Rhône Villages',
    vintage: 2020,
    category: 'red',
    price: 18.95,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&q=80'],
    description: 'Een warme, fruitgedreven rode uit Zuid-Rhône. Uitstekende waarde voor dagelijkse consumptie.',
    tastingNotes: 'Rijpe rode bessen, kruiden de Provence en zwarte peper. Medium body met zachte tannines.',
    foodPairing: 'Heerlijk bij gegrilde groenten, ratatouille of casual pasta gerechten.',
    region: 'Rhône Vallei, Frankrijk',
    grapeVariety: ['Grenache', 'Syrah', 'Mourvèdre'],
    alcoholPercentage: 14.0,
    volume: 750,
    servingTemperature: '15-17°C',
    inStock: true,
    featured: false,
  },

  // White Wines
  {
    id: '5',
    slug: 'chablis-premier-cru-2019',
    name: 'Chablis Premier Cru',
    vintage: 2019,
    category: 'white',
    price: 38.50,
    image: 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?w=800&q=80'],
    description: 'Zuivere, mineraal gedreven Chardonnay uit Bourgogne. Onoaked en elegant.',
    tastingNotes: 'Groene appel, citroenschil en natte stenen. Knapperige zuurgraad met een zoute afdronk.',
    foodPairing: 'Uitzonderlijk bij oesters, zeevruchten of geitenkaas.',
    region: 'Bourgogne, Frankrijk',
    grapeVariety: ['Chardonnay'],
    alcoholPercentage: 12.5,
    volume: 750,
    servingTemperature: '10-12°C',
    inStock: true,
    featured: true,
  },
  {
    id: '6',
    slug: 'alsace-riesling-2021',
    name: 'Alsace Riesling',
    vintage: 2021,
    category: 'white',
    price: 24.95,
    image: 'https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=800&q=80'],
    description: 'Aromatische en verfrissende Riesling uit de Elzas met perfecte balans.',
    tastingNotes: 'Witte perzik, limoen en petroleumnoten. Off-dry met levendige zuurgraad.',
    foodPairing: 'Perfect bij Aziatische keuken, varkensvlees of pittige gerechten.',
    region: 'Elzas, Frankrijk',
    grapeVariety: ['Riesling'],
    alcoholPercentage: 12.0,
    volume: 750,
    servingTemperature: '8-10°C',
    inStock: true,
    featured: false,
  },
  {
    id: '7',
    slug: 'sancerre-2022',
    name: 'Sancerre',
    vintage: 2022,
    category: 'white',
    price: 28.95,
    image: 'https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1568213816046-0ee1c42bd559?w=800&q=80'],
    description: 'Klassieke Loire Vallei Sauvignon Blanc met precisie en frisheid.',
    tastingNotes: 'Grapefruit, kruisbes en verse kruiden. Pittig en mineraal.',
    foodPairing: 'Uitstekend bij geitenkaas, schaaldieren of salades.',
    region: 'Loire Vallei, Frankrijk',
    grapeVariety: ['Sauvignon Blanc'],
    alcoholPercentage: 13.0,
    volume: 750,
    servingTemperature: '8-10°C',
    inStock: true,
    featured: false,
  },
  {
    id: '8',
    slug: 'soave-classico-2022',
    name: 'Soave Classico',
    vintage: 2022,
    category: 'white',
    price: 16.50,
    image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=800&q=80'],
    description: 'Lichte en elegante witte uit Veneto. Geweldige dagelijkse drinkwijn.',
    tastingNotes: 'Amandel, witte bloemen en citrus. Knapperig en verfrissend.',
    foodPairing: 'Past goed bij lichte pasta, vis of antipasti.',
    region: 'Veneto, Italië',
    grapeVariety: ['Garganega'],
    alcoholPercentage: 12.5,
    volume: 750,
    servingTemperature: '8-10°C',
    inStock: true,
    featured: false,
  },

  // Rosé Wines
  {
    id: '9',
    slug: 'provence-rose-2023',
    name: 'Provence Rosé',
    vintage: 2023,
    category: 'rosé',
    price: 21.95,
    image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=800&q=80'],
    description: 'Bleke, elegante rosé uit de Provence. Perfect voor warm weer.',
    tastingNotes: 'Aardbei, watermeloen en kruiden. Droog en verfrissend.',
    foodPairing: 'Ideaal bij mediterrane keuken, salades of als aperitief.',
    region: 'Provence, Frankrijk',
    grapeVariety: ['Grenache', 'Cinsault', 'Syrah'],
    alcoholPercentage: 12.5,
    volume: 750,
    servingTemperature: '8-10°C',
    inStock: true,
    featured: false,
  },
  {
    id: '10',
    slug: 'bandol-rose-2022',
    name: 'Bandol Rosé',
    vintage: 2022,
    category: 'rosé',
    price: 32.50,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80'],
    description: 'Gestructureerde, verouderende rosé uit de prestigieuze Bandol appellation.',
    tastingNotes: 'Rode bessen, kruiden en mineralen. Voller body met uitstekende diepte.',
    foodPairing: 'Combineert goed met bouillabaisse, gegrilde vis of ratatouille.',
    region: 'Provence, Frankrijk',
    grapeVariety: ['Mourvèdre', 'Grenache', 'Cinsault'],
    alcoholPercentage: 13.0,
    volume: 750,
    servingTemperature: '10-12°C',
    inStock: true,
    featured: false,
  },

  // Sparkling Wines
  {
    id: '11',
    slug: 'champagne-brut-nv',
    name: 'Champagne Brut NV',
    vintage: 2020,
    category: 'sparkling',
    price: 52.95,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80'],
    description: 'Klassieke non-vintage Champagne met fijne bubbels en elegantie.',
    tastingNotes: 'Brioche, appel en citrus. Romige mousse met gebalanceerde zuurgraad.',
    foodPairing: 'Perfect als aperitief of bij zeevruchten en lichte hapjes.',
    region: 'Champagne, Frankrijk',
    grapeVariety: ['Chardonnay', 'Pinot Noir', 'Pinot Meunier'],
    alcoholPercentage: 12.0,
    volume: 750,
    servingTemperature: '6-8°C',
    inStock: true,
    featured: true,
  },
  {
    id: '12',
    slug: 'prosecco-superiore-nv',
    name: 'Prosecco Superiore',
    vintage: 2023,
    category: 'sparkling',
    price: 15.95,
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80'],
    description: 'Verse en fruitige Prosecco uit de Valdobbiadene heuvels.',
    tastingNotes: 'Peer, witte bloemen en honing. Lichte, verfrissende bubbels.',
    foodPairing: 'Heerlijk bij aperitivo snacks, lichte pasta of fruit desserts.',
    region: 'Veneto, Italië',
    grapeVariety: ['Glera'],
    alcoholPercentage: 11.0,
    volume: 750,
    servingTemperature: '6-8°C',
    inStock: true,
    featured: false,
  },
  {
    id: '13',
    slug: 'cremant-de-bourgogne-nv',
    name: 'Crémant de Bourgogne',
    vintage: 2021,
    category: 'sparkling',
    price: 22.95,
    image: 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?w=800&q=80',
    images: ['https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?w=800&q=80'],
    description: 'Uitstekende waarde mousserende wijn gemaakt volgens traditionele methode uit Bourgogne.',
    tastingNotes: 'Appel, hazelnoot en toast. Fijne bubbels met elegante structuur.',
    foodPairing: 'Veelzijdig bij hapjes, zeevruchten of viering toost.',
    region: 'Bourgogne, Frankrijk',
    grapeVariety: ['Chardonnay', 'Pinot Noir'],
    alcoholPercentage: 12.5,
    volume: 750,
    servingTemperature: '6-8°C',
    inStock: true,
    featured: false,
  },
];

export const getFeaturedWines = () => mockWines.filter(wine => wine.featured).slice(0, 4);
export const getWinesByCategory = (category: string) => 
  mockWines.filter(wine => wine.category === category);
export const getWineBySlug = (slug: string) => 
  mockWines.find(wine => wine.slug === slug);
